[Build]
History=yes
CacheDirectory=mkosi.cache
UseSubvolumes=yes
WithNetwork=true

[Output]
ImageId=CustomOS
OutputDirectory=mkosi.output
Format=disk
SplitArtifacts=yes

[Distribution]
Distribution=arch

# [Validation]
# SecureBoot=true
# SecureBootAutoEnroll=true
# SecureBootSignTool=systemd-sbsign
# SecureBootKey=./mkosi.key
# SecureBootCertificate=./mkosi.crt

# SignExpectedPcr=true
# VerityKey=./mkosi.key
# VerityCertificate=./mkosi.crt

[Content]
Bootable=true
BaseTrees=%O/base
UnifiedKernelImages=true
UnifiedKernelImageFormat=%i_%v
KernelCommandLine=rw vt.handoff=1 iommu=pt intel_iommu=on amd_iommu=on quiet loglevel=0 systemd.show_status=0 rootflags=noexec,nodev,nosuid rd.systemd.mount-extra=/dev/disk/by-partlabel/esp:/boot:vfat:rw