[Build]
History=yes
CacheDirectory=mkosi.cache
UseSubvolumes=true
WithNetwork=true

[Output]
ImageId=CustomOS
OutputDirectory=mkosi.output
Format=disk
SplitArtifacts=yes

[Distribution]
Distribution=arch

[Validation]
SecureBoot=false
SecureBootAutoEnroll=false
SecureBootSignTool=systemd-sbsign
# SecureBootKey=./mkosi.key
# SecureBootCertificate=./mkosi.crt

# SignExpectedPcr=true
# VerityKey=./mkosi.key
# VerityCertificate=./mkosi.crt

[Content]
Bootable=true
BaseTrees=%O/base
UnifiedKernelImages=auto
UnifiedKernelImageFormat=%i_%v
KernelCommandLine=rw
KernelModulesInitrd=true
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=default