[Build]
History=yes
CacheDirectory=mkosi.cache
UseSubvolumes=true
WithNetwork=true

[Output]
OutputDirectory=mkosi.output
Format=disk
SplitArtifacts=true

[Distribution]
Distribution=arch

[Validation]
SecureBoot=false
SecureBootAutoEnroll=true
SecureBootSignTool=systemd-sbsign
# SecureBootKey=./mkosi.key
# SecureBootCertificate=./mkosi.crt

# SignExpectedPcr=true
# VerityKey=./mkosi.key
# VerityCertificate=./mkosi.crt

[Content]
Bootable=true
UnifiedKernelImages=auto
KernelCommandLine=rw lsm=landlock,lockdown,yama,integrity,apparmor,bpf nowatchdog quiet splash
KernelModulesInitrd=true
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=default

[Runtime]
VirtualMachineMonitor=qemu
CPUs=4
RAM=4G
TPM=true
Console=gui
