[Content]
Packages=
    acl
    archlinux-keyring
    attr
    audit
    base
    bash
    bc
    bcachefs-tools
    binutils
    brotli
    btrfs-progs
    bzip2
    ca-certificates
    ca-certificates-mozilla
    ca-certificates-utils
    coreutils
    cryptsetup
    curl
    dbus
    dbus-broker
    dbus-broker-units
    device-mapper
    dhcpcd
    diffutils
    dosfstools
    e2fsprogs
    efibootmgr
    exfatprogs
    f2fs-tools
    fatresize
    file
    filesystem
    findutils
    fish
    fwupd
    gawk
    glibc
    gmp
    gnupg
    gnutls
    gptfdisk
    grep
    gzip
    hdparm
    iana-etc
    iproute2
    iptables
    ntfs-3g
    iputils
    json-c
    kbd
    keyutils
    kmod
    ldns
    leancrypto
    less
    lz4
    lzo
    lzop
    man-db
    man-pages
    mtools
    nano
    ncurses
    ndisc6
    net-tools
    nettle
    nftables
    nvme-cli
    openssh
    openssl
    p11-kit
    pam
    pambase
    parted
    pcre
    pcre2
    perl
    pcsclite
    pinentry
    polkit
    procps-ng
    psmisc
    rsync
    sed
    shadow
    slang
    smartmontools
    sqlite
    squashfs-tools
    sshfs
    sudo
    sysfsutils
    systemd
    systemd-libs
    systemd-resolvconf
    systemd-sysvcompat
    systemd-ukify
    tar
    tcpdump
    terminus-font
    thin-provisioning-tools
    tpm2-tools
    tpm2-tss
    tzdata
    usbutils
    util-linux
    util-linux-libs
    vim
    vim-runtime
    which
    xdg-utils
    xfsprogs
    xz
    zlib
    zsh
    zstd