[Content]
Packages=
    ddcutil
    intel-media-driver
    libva
    libva-mesa-driver
    libva-nvidia-driver
    libva-utils
    mesa
    mesa-utils
    switcheroo-control
    vpl-gpu-rt
    vulkan-icd-loader
    vulkan-intel
    vulkan-radeon
    vulkan-tools