[Content]
Packages=
    ffmpeg
    ffmpegthumbs
    flac
    lame
    libsamplerate
    libsndfile
    libvorbis
    mpg123
    opus
    pipewire
    pipewire-alsa
    pipewire-ffado
    pipewire-jack
    pipewire-libcamera
    pipewire-pulse
    pipewire-roc
    pipewire-v4l2
    pipewire-zeroconf
    sof-firmware
    wireplumber