[Content]
Packages=
    avahi
    b43-fwcutter
    bluez-libs
    broadcom-wl
    cifs-utils
    dnsmasq
    dnssec-anchors
    ethtool
    iproute2
    iw
    networkmanager
    nfs-utils
    samba
    smbclient
    ufw
    ufw-extras
    wireless-regdb