[Content]
Packages=
    breeze-plymouth
    dolphin
    dolphin-plugins
    flatpak
    hicolor-icon-theme
    kde-inotify-survey
    kdegraphics-thumbnailers
    kdenetwork-filesharing
    kio-extras
    kio-gdrive
    kio-zeroconf
    konsole
    plasma-meta
    plymouth-kcm
    sddm
    sddm-kcm
    xdg-desktop-portal
    xdg-desktop-portal-kde