[Content]
Packages=
    dolphin
    dolphin-plugins
    hicolor-icon-theme
    kde-inotify-survey
    kdenetwork-filesharing
    kio-extras
    kio-gdrive
    kio-zeroconf
    plasma-meta
    sddm
    sddm-kcm