[Content]
Packages=
    apparmor
    btrfs-progs
    btrfsmaintenance
    ca-certificates
    cryptsetup
    curl
    dbus
    dosfstools
    e2fsprogs
    efitools
    erofs-utils
    exfatprogs
    fish
    flatpak
    gdisk
    iproute2
    nvme-cli
    smartmontools
    systemd
    systemd-resolvconf
    tpm2-tss
    tpm2-tools
    tuned-ppd
    tzdata
    udev
    usbip
    wireguard-tools
    xdg-desktop-portal-gtk
    xdg-user-dirs
    zram-generator
    zstd
    xfsprogs