[Content]
Packages=
    ddcutil
    libva
    libva-utils
    libva-intel-driver
    libva-mesa-driver
    libva-nvidia-driver
    mesa
    mesa-utils
    nvidia-open-dkms
    switcheroo-control
    vpl-gpu-rt
    vulkan-icd-loader
    vulkan-intel
    vulkan-radeon
    vulkan-tools
    xorg-wayland