[Content]
Packages=
    ffmpeg
    pipewire
    pipewire-alsa
    pipewire-ffado
    pipewire-jack
    pipewire-libcamera
    pipewire-pulse
    pipewire-roc
    pipewire-v4l2
    pipewire-zeroconf
    sof-firmware
    wireplumber
