[Config]
Dependencies=base

[Output]
Format=sysext
Overlay=yes
ManifestFormat=json
ImageVersion=

[Content]
BaseTrees=%O/base
Packages=
    dolphin-plugins
    dolpin
    kde-inotify-survey
    kdenetwork-filesharing
    kio-extras
    kio-gdrive
    kio-zeroconf
    plasma-meta
    sddm
    sddm-kcm